-- StockWise baseline schema (multi-tenant). Databases created before Flyway was introduced are
-- baselined at this version (spring.flyway.baseline-on-migrate), so this script only runs on empty databases.

CREATE TABLE organizations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255)  NOT NULL,
    slug            VARCHAR(63)   NOT NULL,
    description     VARCHAR(1000),
    contact_email   VARCHAR(255),
    status          VARCHAR(20)   NOT NULL,
    setup_completed BOOLEAN       NOT NULL,
    created_at      TIMESTAMP(6)  NOT NULL,
    updated_at      TIMESTAMP(6)  NOT NULL,
    CONSTRAINT uk_organizations_slug UNIQUE (slug),
    CONSTRAINT organizations_status_check CHECK (status IN ('ACTIVE', 'SUSPENDED'))
);

CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    email           VARCHAR(255) NOT NULL,
    password        VARCHAR(255) NOT NULL,
    role            VARCHAR(255) NOT NULL,
    status          VARCHAR(20)  NOT NULL,
    organization_id BIGINT,
    created_at      TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT fk_users_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT users_role_check CHECK (role IN ('SUPER_ADMIN', 'ADMIN', 'STAFF')),
    CONSTRAINT users_status_check CHECK (status IN ('PENDING', 'ACTIVE', 'REJECTED', 'DISABLED'))
);

CREATE TABLE categories (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    description     TEXT,
    organization_id BIGINT       NOT NULL,
    CONSTRAINT uk_categories_org_name UNIQUE (organization_id, name),
    CONSTRAINT fk_categories_organization FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE TABLE products (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255)   NOT NULL,
    description     TEXT,
    sku             VARCHAR(255)   NOT NULL,
    price           NUMERIC(12, 2) NOT NULL,
    quantity        INTEGER        NOT NULL,
    minimum_stock   INTEGER        NOT NULL,
    category_id     BIGINT,
    organization_id BIGINT         NOT NULL,
    created_at      TIMESTAMP(6)   NOT NULL,
    updated_at      TIMESTAMP(6),
    CONSTRAINT uk_products_org_sku UNIQUE (organization_id, sku),
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT fk_products_organization FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE TABLE refresh_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT,
    token       VARCHAR(64)              NOT NULL,
    expiry_date TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    revoked     BOOLEAN                  NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_refresh_tokens_token UNIQUE (token),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX idx_refresh_tokens_user ON refresh_tokens (user_id);

CREATE TABLE invitations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token           VARCHAR(64)  NOT NULL,
    email           VARCHAR(255) NOT NULL,
    name            VARCHAR(255),
    role            VARCHAR(20)  NOT NULL,
    organization_id BIGINT       NOT NULL,
    expires_at      TIMESTAMP(6) NOT NULL,
    accepted_at     TIMESTAMP(6),
    created_at      TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_invitations_token UNIQUE (token),
    CONSTRAINT fk_invitations_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT invitations_role_check CHECK (role IN ('SUPER_ADMIN', 'ADMIN', 'STAFF'))
);

CREATE TABLE subscription_requests (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_name VARCHAR(255)  NOT NULL,
    contact_name      VARCHAR(255)  NOT NULL,
    contact_email     VARCHAR(255)  NOT NULL,
    contact_phone     VARCHAR(50),
    has_existing_data BOOLEAN       NOT NULL,
    message           TEXT,
    status            VARCHAR(20)   NOT NULL,
    review_note       VARCHAR(1000),
    organization_id   BIGINT,
    created_at        TIMESTAMP(6)  NOT NULL,
    reviewed_at       TIMESTAMP(6),
    CONSTRAINT fk_subscription_requests_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT subscription_requests_status_check CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);
