-- Optimistic locking for product edits: concurrent updates fail with 409 instead of silently overwriting.
ALTER TABLE products ADD COLUMN version BIGINT DEFAULT 0 NOT NULL;

-- Every session belongs to a user (the old one-token-per-user column allowed NULL).
DELETE FROM refresh_tokens WHERE user_id IS NULL;
ALTER TABLE refresh_tokens ALTER COLUMN user_id SET NOT NULL;

-- Indexes for tenant-scoped lookups and foreign keys
CREATE INDEX idx_users_organization ON users (organization_id);
CREATE INDEX idx_products_category ON products (category_id);
CREATE INDEX idx_invitations_organization ON invitations (organization_id);
CREATE INDEX idx_invitations_email ON invitations (email);
CREATE INDEX idx_subscription_requests_status ON subscription_requests (status);

-- Stock ledger: one row per change to a product's quantity. Product and user details are copied onto the row,
-- so the history stays readable after a product is deleted or a user is removed.
CREATE TABLE stock_movements (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id   BIGINT       NOT NULL,
    product_id        BIGINT,
    product_sku       VARCHAR(255) NOT NULL,
    product_name      VARCHAR(255) NOT NULL,
    type              VARCHAR(20)  NOT NULL,
    quantity_change   INTEGER      NOT NULL,
    quantity_after    INTEGER      NOT NULL,
    notes             VARCHAR(500),
    performed_by_id   BIGINT,
    performed_by_name VARCHAR(255),
    created_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_stock_movements_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_stock_movements_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE SET NULL,
    CONSTRAINT fk_stock_movements_user FOREIGN KEY (performed_by_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT stock_movements_type_check CHECK (type IN ('INITIAL', 'STOCK_IN', 'STOCK_OUT', 'ADJUSTMENT', 'IMPORT'))
);
CREATE INDEX idx_stock_movements_product ON stock_movements (organization_id, product_id, created_at);
